### PR TITLE
Fix incorrect cursor movement

### LINKED ISSUE #888: 🐛 Overlapping terminal output
## Environment

<details>
<summary> $ rome rage --summary</summary>

```
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Yasser/bin:/Users/Yasser/bin"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
    USER: "Yasser"
  }

User Config
  unset

Rome Version
  0.0.26-dev

Node Version
  14.6.0

Platform
  darwin x64 19.5.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 142
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/Yasser/Dev/rome"
    silent: false
  }
```
</details>

## Steps To Reproduce

Run `./rome check`

Screen Shot 2020-07-25 at 8 55 20 AM

## Expected Results

Old lines should be fully cleared.

### PR DESCRIPTION
**Pull request by sebmck**
## Summary

Fixes #888. I added some tests for cursor movement too. It includes both what we think is the current buffer of the terminal and the raw ANSI output.

On a separate note I'm pretty pleased with the API for replacing/removing lines. Makes it really easy. Although the `LogOptions` property names could use some tweaking.

## Test Plan

Added tests and verified the snapshot accuracy.

### CODE REVIEW

File: packages/cli-reporter/stream.ts [hunk 1]
```diff
@@ -26,17 +35,16 @@ export function getLeadingNewlineCount({state}: ReporterStreamAttached): number
...
 	lineDiff: number;
 	bufferIndex: number;
 } {
-	let lineDiff = state.currentLine - targetLine;
+	let lineDiff = ob1Get0(ob1Sub(state.currentLine, targetLine));
 	let bufferIndex = state.buffer.length - lineDiff;
 
 	if (!state.leadingNewline) {
 		bufferIndex--;
-		lineDiff--;
```
Comment (sebmck) [inline packages/cli-reporter/stream.ts:39]: Removing this line was actually the only fix for #888. I forgot to put it in a separate commit.
