### PR TITLE
Flags description

### LINKED ISSUE #809: Missing description for commands flags
Description:

Missing description for flags that belong to a command

## Steps To Reproduce
1. run `scripts/dev-rome check --help`
2. check result

Screenshot 2020-07-14 at 15 21 41

## Expected Results

There should be a description to explain the option

### PR DESCRIPTION
**Pull request by ematipico**
Closes #809

### CODE REVIEW

File: packages/@romefrontend/core/server/commands/check.ts [hunk 1]
```diff
@@ -39,9 +39,24 @@ export default createServerCommand<Flags>({
...
+			formatOnly: consumer.get(
+				"formatOnly",
+				{
+					description: "only applies format changes to the entire project",
+				},
+			).asBoolean(false),
+			changed: consumer.get(
+				"changed",
+				{
+					description: "shows what's changed from the main branch",
```
Comment (sebmck) [inline packages/@romefrontend/core/server/commands/check.ts:57]:
```suggestion
					description: "only include files that have changed from the specified branch/commit (defaults to main)",
```

File: packages/@romefrontend/core/server/commands/check.ts [hunk 2]
```diff
@@ -39,9 +39,24 @@ export default createServerCommand<Flags>({
 			decisions: consumer.get("decisions").asImplicitArray().map((item) =>
 				item.asString()
 			),
-			apply: consumer.get("apply").asBoolean(false),
-			formatOnly: consumer.get("formatOnly").asBoolean(false),
-			changed: consumer.get("changed").asStringOrVoid(),
+			apply: consumer.get(
+				"apply",
+				{
+					description: "autofixes and format are applied to the entire project",
```
Comment (sebmck) [inline packages/@romefrontend/core/server/commands/check.ts:45]:
```suggestion
					description: "recommended autofixes and formatting is applied",
```

File: packages/@romefrontend/core/server/commands/check.ts [hunk 3]
```diff
@@ -39,9 +39,24 @@ export default createServerCommand<Flags>({
...
+				},
+			).asBoolean(false),
+			formatOnly: consumer.get(
+				"formatOnly",
+				{
+					description: "only applies format changes to the entire project",
```
Comment (sebmck) [inline packages/@romefrontend/core/server/commands/check.ts:51]:
```suggestion
					description: "only formatting is applied",
```

File: packages/@romefrontend/core/server/commands/ci.ts [hunk 4]
```diff
@@ -23,7 +23,12 @@ export default createServerCommand({
 	examples: [],
 	defineFlags(consumer: Consumer): Flags {
 		return {
-			fix: consumer.get("fix").asBoolean(false),
+			fix: consumer.get(
+				"fix",
+				{
+					description: "applies format and autofixes to the entire project",
```
Comment (sebmck) [inline packages/@romefrontend/core/server/commands/ci.ts:29]:
```suggestion
					description: "enables --update-snapshots for test, and --apply for the lint command",
```

**Comment by sebmck** [comment]
Thank you!
