### PR TITLE
fix: match case insensitive license word (#1064)

### LINKED ISSUE #1064: 🐛 parse/spdxLicense errors during rome init
## Environment

```
$ rome rage --summary
Environment Variables
  Object {
    TERM: "xterm-256color"
    TERM_PROGRAM: "Apple_Terminal"
  }

User Config
  unset

Rome Version
  10.0.4-beta

Node Version
  12.18.3

Platform
  darwin x64 19.6.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 8
    columns: 82
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/myuser/dev/myoldproject"
    realCwd: "/Users/myuser/dev/myoldproject"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 26_583_040
      pid: 7_661
      uptime: 0.265367234
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 26_583_040
        ownedBytes: 0
        ownedFileCount: 0
        pid: 7_661
        uptime: 0.265289183
      }
    ]
  }


✨  Done in 0.56s.
```

## Steps To Reproduce

1. run `rome init` in existing project.
2. look at generated errors:
```
 Welcome to Rome! Let's get you started... 

[1/2] Generating .editorconfig

 node_modules/dom-storage/package.json:16:19 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━

  ✖ Expected token ParenClose but got Word

 node_modules/xmldom/package.json:21:24 parse/spdxLicense ━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Expected token ParenClose but got Word

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 2 problems
```

It seems like it fails to parse these licenses:
1. `(MIT or Apache-2.0)` from `dom-storage` 2.1.0 (latest) here https://git.coolaj86.com/coolaj86/dom-storage.js/src/branch/master/package.json#L16
1. `(LGPL-2.0 or MIT)` from `xmldom` version 0.1.31 here  https://github.com/xmldom/xmldom/blob/91e456310880c24ae97629bd5754f96ffcb623c5/package.json#L21

## Expected Results

No errors.

### PR DESCRIPTION
**Pull request by noelebrun**
## Summary

Closes #1064

Matches the separator words in the license (such as `or` or `and`) in a case insensitive manner.

### Folder structure
- **/rome** *(Rome's repository)*
- **/dom-storage.js** *(https://git.coolaj86.com/coolaj86/dom-storage.js/)* 
- **/xmldom** *https://github.com/xmldom/xmldom/()*

#### Commands

- `cd dom-storage.js`
- `../rome/rome init`

#### Output

```

 Welcome to Rome! Let's get you started... 

 Files created ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  - .config/rome.rjson: Your project configuration. Documentation: https://romefrontend.dev/#project-configuration
  - .editorconfig: Sets editor formatting and indentation options. Documentation: https://editorconfig.org/

 What next? ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  1. Setup an editor extension
     Get live errors as you type and format when you save. Learn more: https://romefrontend.dev/#editor-integration

  2. Try a command
     rome check is used to validate your code, verify formatting, and check for lint errors. Run rome --help for a full list of commands and flags.

  3. Read documentation
     Our website serves as a comprehensive source of guides and documentation https://romefrontend.dev/

  4. Get involved in the community
     Ask questions, get support, or contribute by participating on GitHub (https://github.com/romefrontend/rome) or our community Discord (https://discord.gg/rome)

```

#### Commands

- `cd xmldom`
- `git checkout tags/v0.1.31`
- `../rome/rome init`

#### Output

```

 package.json:16:59 parse/manifest ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unknown web property at contributors[0]

    14 │   "maintainers": [{"name": "jindw","email": "jindw@xidea.org","url": "http://www.xidea.org"}],
    15 │   "contributors": [
  > 16 │     {"name" : "Yaron Naveh","email" : "yaronn01@gmail.com","web" : "http://webservices20.blogspot.com/"},
       │                                                            ^^^^^^
    17 │     {"name" : "Harutyun Amirjanyan","email" : "amirjanyan@gmail.com","web" : "https://github.com/nightwing"},
    18 │     {"name" : "Alan Gutierrez","email" : "alan@prettyrobots.com","web" : "http://www.prettyrobots.com/"}

 package.json:17:69 parse/manifest ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unknown web property at contributors[1]

    15 │   "contributors": [
    16 │     {"name" : "Yaron Naveh","email" : "yaronn01@gmail.com","web" : "http://webservices20.blogspot.com/"},
  > 17 │     {"name" : "Harutyun Amirjanyan","email" : "amirjanyan@gmail.com","web" : "https://github.com/nightwing"},
       │                                                                      ^^^^^^
    18 │     {"name" : "Alan Gutierrez","email" : "alan@prettyrobots.com","web" : "http://www.prettyrobots.com/"}
    19 │   ],

 package.json:18:65 parse/manifest ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unknown web property at contributors[2]

    16 │     {"name" : "Yaron Naveh","email" : "yaronn01@gmail.com","web" : "http://webservices20.blogspot.com/"},
    17 │     {"name" : "Harutyun Amirjanyan","email" : "amirjanyan@gmail.com","web" : "https://github.com/nightwing"},
  > 18 │     {"name" : "Alan Gutierrez","email" : "alan@prettyrobots.com","web" : "http://www.prettyrobots.com/"}
       │                                                                  ^^^^^^
    19 │   ],
    20 │   "bugs": {"email": "jindw@xidea.org","url": "http://github.com/jindw/xmldom/issues"},

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✖ Found 3 problems

```

*(Those errors are expected, this repository is using invalid `package.json` fields. But the errors about the license aren't there anymore)*

### CODE REVIEW

File: internal/codec-spdx-license/parse.ts [hunk 1]
```diff
@@ -96,12 +96,13 @@ const createSPDXLicenseParser = createParser<SPDXParserTypes>({
 
 		if (isWordChar(char)) {
 			const [value, end] = parser.readInputFrom(index, isWordChar);
+			const upperCasedValue = value.toUpperCase ? value.toUpperCase() : value;
```
Comment (sebmck) [inline internal/codec-spdx-license/parse.ts:99]: Why the ternary for `value.toUpperCase`? It should always exist.

Comment (noelebrun) [reply internal/codec-spdx-license/parse.ts]: Indeed. Had some issues at some point with undefined value, but that was probably due to something else. Just re-tried in a few repositories and it work fine without the check.

**Comment by sebmck** [comment]
Looks good, thank you!
